/**
 * Units: per-unit stock for a project listing, so the concierge can answer
 * "which units are available and how much" instead of sending people to a page.
 *
 * Source of truth is `src/data/units.json`, generated by
 * `scripts/curate/build-units.py` from the developer's own inventory sheet.
 * Every number in it is printed in that sheet — nothing here estimates a price
 * (TAQEEM), and a unit with no cash price is dropped rather than guessed at.
 *
 * Mirrors inventory.mjs: same lazy read + mtime reload, same "the file is
 * generated, we only ever read it" contract.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const WORKTREE_UNITS = path.resolve(HERE, '../../../src/data/units.json');

export const RELOAD_MS = 10 * 60 * 1000;
export const STAT_MS = 30 * 1000;

/** Payment plans, in the order a buyer meets them. */
export const PLANS = ['cash', 'half', 'year', 'twoYear'];
export const PLAN_LABELS = {
  cash: { en: 'cash', ar: 'كاش' },
  half: { en: '6-month instalments', ar: 'تقسيط ٦ أشهر' },
  year: { en: '1-year instalments', ar: 'تقسيط سنة' },
  twoYear: { en: '2-year instalments / finance', ar: 'تقسيط سنتين أو تمويل' },
};

const fmt = (n) => (typeof n === 'number' ? n.toLocaleString('en-US') : null);

/** "SAR 1,069,607" / "1,069,607 ر.س" — same digits both locales, like inventory.mjs. */
export function money(amount, lang = 'en') {
  if (typeof amount !== 'number') return null;
  return lang === 'ar' ? `${fmt(amount)} ر.س` : `SAR ${fmt(amount)}`;
}

function normalise(s) {
  return String(s ?? '')
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u064B-\u065F\u0670]/g, '')   // Arabic diacritics
    .replace(/[أإآ]/g, 'ا')
    .replace(/[ىي]/g, 'ي')
    .replace(/ة/g, 'ه')
    .replace(/[^a-z0-9\u0600-\u06FF]+/g, ' ')
    .trim();
}

export function createUnits({ file = WORKTREE_UNITS, now = Date.now } = {}) {
  let doc = null;
  let loadedAt = 0;
  let statedAt = 0;
  let mtime = 0;

  function read() {
    const raw = JSON.parse(fs.readFileSync(file, 'utf8'));
    const units = (raw.units || []).filter((u) => typeof u?.price?.cash === 'number');
    return { ...raw, units };
  }

  function load() {
    const t = now();
    if (doc && t - loadedAt < RELOAD_MS) {
      // Cheap stat so an edit shows up long before the full reload window.
      if (t - statedAt > STAT_MS) {
        statedAt = t;
        try {
          const m = fs.statSync(file).mtimeMs;
          if (m !== mtime) { doc = read(); mtime = m; loadedAt = t; }
        } catch { /* keep what we have */ }
      }
      return doc;
    }
    try {
      doc = read();
      mtime = fs.statSync(file).mtimeMs;
    } catch {
      doc = doc ?? { units: [] };
    }
    loadedAt = t;
    statedAt = t;
    return doc;
  }

  /** Every unit belonging to a listing id (BONA-W014). */
  function forListing(listingId) {
    const d = load();
    if (!listingId || d.listingId !== listingId) return null;
    return d;
  }

  /**
   * Filter the stock. Every argument is optional; unknown values are ignored
   * rather than throwing, because these come from a language model.
   */
  function search({
    listingId = null, beds = null, minBeds = null, maxBeds = null,
    building = null, floor = null, facing = null, unitClass = null,
    maidRoom = null, minPrice = null, maxPrice = null, plan = 'cash',
    minArea = null, maxArea = null, query = null, limit = 8,
  } = {}) {
    const d = load();
    if (!d.units?.length) return { doc: null, units: [], total: 0 };
    if (listingId && d.listingId !== listingId) return { doc: null, units: [], total: 0 };

    const p = PLANS.includes(plan) ? plan : 'cash';
    const q = query ? normalise(query) : null;
    const num = (v) => (typeof v === 'number' && Number.isFinite(v) ? v : null);

    let out = d.units.filter((u) => {
      const price = u.price?.[p] ?? u.price?.cash;
      if (num(beds) !== null && u.beds !== beds) return false;
      if (num(minBeds) !== null && !(u.beds >= minBeds)) return false;
      if (num(maxBeds) !== null && !(u.beds <= maxBeds)) return false;
      if (building && normalise(u.building) !== normalise(building)) return false;
      if (floor !== null && floor !== undefined && floor !== '') {
        const f = normalise(floor);
        const hit = normalise(u.floor?.en) === f || normalise(u.floor?.ar) === f
          || (num(floor) !== null && u.floorIndex === floor);
        if (!hit) return false;
      }
      if (facing && !normalise(u.facing?.en).includes(normalise(facing))
        && !normalise(u.facing?.ar).includes(normalise(facing))) return false;
      if (unitClass && normalise(u.class) !== normalise(unitClass)) return false;
      if (maidRoom === true && !u.maidRoom) return false;
      if (maidRoom === false && u.maidRoom) return false;
      if (num(minPrice) !== null && !(price >= minPrice)) return false;
      if (num(maxPrice) !== null && !(price <= maxPrice)) return false;
      if (num(minArea) !== null && !(u.areaSqm >= minArea)) return false;
      if (num(maxArea) !== null && !(u.areaSqm <= maxArea)) return false;
      if (q) {
        const hay = normalise([
          u.ref, u.building, u.unit, u.floor?.en, u.floor?.ar, u.facing?.en, u.facing?.ar,
          u.class, u.type?.en, u.type?.ar, u.feature?.en, u.feature?.ar,
        ].filter(Boolean).join(' '));
        if (!hay.includes(q)) return false;
      }
      return true;
    });

    const total = out.length;
    out = out.sort((a, b) => (a.price?.[p] ?? a.price.cash) - (b.price?.[p] ?? b.price.cash));
    const n = Math.max(1, Math.min(Number(limit) || 8, 20));
    return { doc: d, units: out.slice(0, n), total };
  }

  /** Compact shape handed to the model — flat, short keys, both locales on price. */
  function toRow(u, plan = 'cash') {
    const p = PLANS.includes(plan) ? plan : 'cash';
    const amount = u.price?.[p] ?? u.price?.cash ?? null;
    return {
      ref: u.ref,
      building: u.building,
      unit: u.unit,
      floor_en: u.floor?.en ?? null,
      floor_ar: u.floor?.ar ?? null,
      facing_en: u.facing?.en ?? null,
      facing_ar: u.facing?.ar ?? null,
      beds: u.beds,
      baths: u.baths,
      maid_room: Boolean(u.maidRoom),
      class: u.class,
      area_sqm: u.areaSqm,
      roof_sqm: u.roofSqm || 0,
      outlook_en: u.feature?.en ?? null,
      outlook_ar: u.feature?.ar ?? null,
      plan: p,
      price_en: money(amount, 'en'),
      price_ar: money(amount, 'ar'),
      price_cash_en: money(u.price?.cash, 'en'),
      price_two_year_en: money(u.price?.twoYear, 'en'),
    };
  }

  /** Availability headline: counts and ranges, for "what do you have?" */
  function summary(listingId = null) {
    const d = load();
    if (!d.units?.length) return null;
    if (listingId && d.listingId !== listingId) return null;
    const cash = d.units.map((u) => u.price.cash);
    const areas = d.units.map((u) => u.areaSqm).filter((a) => typeof a === 'number');
    const beds = [...new Set(d.units.map((u) => u.beds).filter((b) => typeof b === 'number'))].sort();
    const byBeds = {};
    for (const b of beds) {
      const rows = d.units.filter((u) => u.beds === b);
      byBeds[b] = {
        count: rows.length,
        from_en: money(Math.min(...rows.map((r) => r.price.cash)), 'en'),
        from_ar: money(Math.min(...rows.map((r) => r.price.cash)), 'ar'),
      };
    }
    return {
      listing_id: d.listingId,
      project_en: d.project?.en ?? null,
      project_ar: d.project?.ar ?? null,
      district_en: d.district?.en ?? null,
      district_ar: d.district?.ar ?? null,
      available: d.units.length,
      buildings: [...new Set(d.units.map((u) => u.building))].sort(),
      beds_available: beds,
      by_beds: byBeds,
      area_min_sqm: areas.length ? Math.min(...areas) : null,
      area_max_sqm: areas.length ? Math.max(...areas) : null,
      price_from_en: money(Math.min(...cash), 'en'),
      price_from_ar: money(Math.min(...cash), 'ar'),
      price_to_en: money(Math.max(...cash), 'en'),
      delivery: d.delivery,
      plans: PLANS.map((k) => ({ key: k, en: PLAN_LABELS[k].en, ar: PLAN_LABELS[k].ar })),
      updated: d.updated,
    };
  }

  return { load, forListing, search, toRow, summary, get file() { return file; } };
}
