import { esc } from './render.mjs';
const detailLabels = {budget:'Budget',area:'Preferred area',property_type:'Property type',timeframe:'Buying timeframe',financing:'Financing',note:'Note',no_match:'External sourcing needed',viewing_requested:'Viewing requested'};
const telegramLabel = s => s==='sent'?'accepted by Telegram; not proof of reading':s==='uncertain'?'not confirmed; check Telegram before resending':s;
const kindLabel = k => ({handoff:'Handoff',followup:'Follow-up',viewing:'Viewing'}[k] ?? k);
const date = t => t ? new Date(t).toLocaleString('en-GB',{timeZone:'Asia/Riyadh'})+' Riyadh' : 'Not scheduled';
export function taskQueue(tasks=[],{page=0,total=tasks.length,limit=100}={}) {
 if(!total)return '<p class="muted">No open handoffs, follow-ups or viewing requests.</p>';
 const pager=`<p>${esc(total)} open tasks · page ${page+1}${page>0?` · <a href="/dashboard?tasks_page=${page-1}#task-queue">Previous</a>`:''}${(page+1)*limit<total?` · <a href="/dashboard?tasks_page=${page+1}#task-queue">Next</a>`:''}</p>`;
 return `<div class="card" id="task-queue" style="padding:20px">${pager}<ul>${tasks.map(t=>`<li><a href="/dashboard/leads/${encodeURIComponent(t.lead_id)}">${esc(t.lead_id)}</a> · ${esc(kindLabel(t.kind))} · ${esc(t.status)} · ${esc(date(t.due_ts))}${t.details.no_match?' · External sourcing needed':''} · Telegram: ${esc(telegramLabel(t.telegram_status))}</li>`).join('')}</ul></div>`;
}
export function leadTasksPanel(leadId,tasks=[],owner=false,notifications=[]) {
 const action='/v1/admin/leads/'+encodeURIComponent(leadId)+'/task';
 const cards=tasks.map(t=>`<div class="card" style="padding:20px;margin-bottom:16px"><h3>${esc(kindLabel(t.kind))} · ${esc(t.status)}</h3><p>${esc(t.reason??'')} · ${esc(date(t.due_ts))}</p><dl class="fields">${Object.entries(t.details).map(([k,v])=>`<dt>${esc(detailLabels[k] ?? k)}</dt><dd dir="auto">${esc(v === true ? 'Yes' : v)}</dd>`).join('')}</dl><p class="muted">Owner: Abdulaziz · Telegram: ${esc(telegramLabel(t.telegram_status))}</p>${owner?`<form method="post" action="${action}"><input type="hidden" name="_dash" value="1"><input type="hidden" name="task_id" value="${esc(t.task_id)}"><label>Status <select name="status">${(t.kind==='viewing'?['requested','confirmed','done','cancelled']:['open','done','cancelled']).map(s=>`<option value="${s}"${s===t.status?' selected':''}>${s}</option>`).join('')}</select></label><label>Date and time (Riyadh, UTC+3; leave blank to keep) <input type="datetime-local" name="due_at"></label><button type="submit">Save task</button></form>`:''}</div>`).join('');
 return `<h2>Handoff, follow-up &amp; viewing</h2><p class="sub">Automatic reminder messages are off. Telegram status is shown on each handoff. A requested viewing is not a confirmed booking.</p>${notifications.length ? '<div class="card" style="padding:20px;margin-bottom:16px"><h3>Owner enquiry notifications</h3>'+notifications.map(n=>'<p>'+esc(date(n.created))+' · '+esc(n.notify_status==='sent'?'Accepted by WhatsApp; not proof of delivery':n.notify_status==='pending'?'Awaiting acknowledgement':'Not confirmed — check WhatsApp before resending')+'</p>').join('')+'</div>' : ''}${cards||'<p>No tasks recorded.</p>'}${owner?`<form class="stack" method="post" action="${action}"><input type="hidden" name="_dash" value="1"><label>New task <select name="kind"><option value="followup">Follow-up</option><option value="viewing">Viewing request</option></select></label><label>Date and time (Riyadh, UTC+3) <input type="datetime-local" name="due_at" required></label><label>Note <textarea name="note" maxlength="500"></textarea></label><button type="submit">Save task; do not send a message</button></form>`:''}`;
}
