// Room / subject vocabulary used to generate bilingual alt text for every image.
// alt = `${room.en} — ${title.en}` / `${room.ar} — ${title.ar}`
export const ROOMS = {
  exterior: { en: 'Exterior', ar: 'الواجهة الخارجية' },
  facade_night: { en: 'Façade at night', ar: 'الواجهة ليلاً' },
  entrance: { en: 'Entrance', ar: 'المدخل' },
  pool: { en: 'Swimming pool', ar: 'المسبح' },
  pool_night: { en: 'Pool at night', ar: 'المسبح ليلاً' },
  indoor_pool: { en: 'Indoor pool', ar: 'المسبح الداخلي' },
  rooftop_pool: { en: 'Rooftop pool', ar: 'مسبح السطح' },
  sea: { en: 'Sea view', ar: 'إطلالة على البحر' },
  beach: { en: 'Private beach', ar: 'الشاطئ الخاص' },
  aerial: { en: 'Aerial view', ar: 'منظر جوي' },
  living: { en: 'Living room', ar: 'غرفة المعيشة' },
  majlis: { en: 'Reception salon', ar: 'المجلس' },
  dining: { en: 'Dining room', ar: 'غرفة الطعام' },
  kitchen: { en: 'Kitchen', ar: 'المطبخ' },
  bedroom: { en: 'Bedroom', ar: 'غرفة النوم' },
  master: { en: 'Master suite', ar: 'الجناح الرئيسي' },
  bathroom: { en: 'Bathroom', ar: 'الحمام' },
  terrace: { en: 'Roof terrace', ar: 'التراس العلوي' },
  balcony: { en: 'Balcony', ar: 'الشرفة' },
  staircase: { en: 'Staircase', ar: 'الدرج' },
  garden: { en: 'Garden', ar: 'الحديقة' },
  courtyard: { en: 'Courtyard', ar: 'الفناء الداخلي' },
  grounds: { en: 'Grounds', ar: 'الحدائق المحيطة' },
  view: { en: 'View', ar: 'الإطلالة' },
  skyline: { en: 'City skyline', ar: 'أفق المدينة' },
  lobby: { en: 'Lobby', ar: 'البهو' },
  lounge: { en: 'Lounge', ar: 'الصالة' },
  bar: { en: 'Bar lounge', ar: 'صالة البار' },
  gym: { en: 'Gym', ar: 'النادي الرياضي' },
  spa: { en: 'Spa', ar: 'السبا' },
  cinema: { en: 'Private cinema', ar: 'السينما الخاصة' },
  tennis: { en: 'Tennis court', ar: 'ملعب التنس' },
  golf: { en: 'Golf course', ar: 'ملعب الجولف' },
  car_lift: { en: 'Sky car lift', ar: 'مصعد السيارات' },
  cafe: { en: 'Café terrace', ar: 'تراس المقهى' },
  event_hall: { en: 'Event hall', ar: 'قاعة المناسبات' },
  study: { en: 'Study', ar: 'المكتب' },
  gallery: { en: 'Gallery', ar: 'الرواق' },
  winter_garden: { en: 'Winter garden', ar: 'الحديقة الشتوية' },
  hall: { en: 'Great hall', ar: 'القاعة الكبرى' },
  tower: { en: 'The tower', ar: 'البرج' },
  render: { en: "Artist's impression", ar: 'تصور معماري' },
  parking: { en: 'Covered parking', ar: 'المواقف المغطاة' },
  satellite: { en: 'Satellite view of the plot', ar: 'صورة جوية للقطعة' },
  satellite_wide: { en: 'Satellite view of the surrounding area', ar: 'صورة جوية للمنطقة المحيطة' },
};
